# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_connexionOK(self):
    self.driver.get("http://localhost/Projet-testeur-logciel-TP/")
    self.driver.set_window_size(1920, 732)
    self.driver.find_element(By.ID, "loginEmail").click()
    self.driver.find_element(By.ID, "loginEmail").send_keys("it@example.com")
    self.driver.find_element(By.ID, "loginPassword").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.ID, "loginSuccess").text == "Connexion réussie. Redirection vers la page d'accueil."
  
  def test_connexionKO(self):
    self.driver.get("http://localhost/Projet-testeur-logciel-TP/")
    self.driver.set_window_size(1920, 732)
    self.driver.find_element(By.ID, "loginEmail").click()
    self.driver.find_element(By.ID, "loginEmail").send_keys("tom@test.fr")
    self.driver.find_element(By.ID, "loginPassword").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.ID, "loginError").text == "Informations de connexion invalides."
  
  def test_inscriptionKO(self):
    self.driver.get("http://localhost/Projet-testeur-logciel-TP/")
    self.driver.set_window_size(1920, 732)
    self.driver.find_element(By.ID, "registerNom").click()
    self.driver.find_element(By.ID, "registerNom").send_keys("deprez")
    self.driver.find_element(By.ID, "registerEmail").click()
    self.driver.find_element(By.ID, "registerEmail").send_keys("tomdeprez@test.fr")
    self.driver.find_element(By.ID, "registerPassword").click()
    self.driver.find_element(By.ID, "registerPassword").send_keys("123456")
    self.driver.find_element(By.ID, "registerPasswordConfirm").click()
    self.driver.find_element(By.ID, "registerPasswordConfirm").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    assert self.driver.find_element(By.ID, "registerError").text == "Les mots de passe ne correspondent pas."
  
  def test_inscriptionOK(self):
    self.driver.get("http://localhost/Projet-testeur-logciel-TP/")
    self.driver.set_window_size(1920, 732)
    self.driver.find_element(By.ID, "registerNom").click()
    self.driver.find_element(By.ID, "registerNom").send_keys("deprez")
    self.driver.find_element(By.ID, "registerEmail").click()
    self.driver.find_element(By.ID, "registerEmail").send_keys("tomdeprez@test.fr")
    self.driver.find_element(By.ID, "registerPassword").click()
    self.driver.find_element(By.ID, "registerPassword").send_keys("123456")
    self.driver.find_element(By.ID, "registerPasswordConfirm").click()
    self.driver.find_element(By.ID, "registerPasswordConfirm").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "registerSuccess").click()
  
